config/routes.rb
Glamstagram::Application.routes.draw do
  
  root :to => "photos#index"
  
  match 'session/:action', :to => 'session'
  
  resources :users
  resources :photos
  resources :tags

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :source, :url, :user_id
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/photos_controller.rb
require 'net/http'
require 'uri'
require 'lib/railsutils/instagram_utils'
require 'instagram'

class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  def index
    if session[:access_token]
      # puts "--------------- HAS SESSION ACCESS TOKEN"
      client = Instagram.client(:access_token => session[:access_token])
      @user = client.user
      @recent_media_items = client.user_recent_media
    elsif
      redirect_to '/session/login'
    end
    
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, :notice => 'Photo was successfully created.' }
        format.json { render :json => @photo, :status => :created, :location => @photo }
      else
        format.html { render :action => "new" }
        format.json { render :json => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, :notice => 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/session_controller.rb
require "instagram"

class SessionController < ApplicationController
  
  def connect
    puts "----------- SESSION CONNECT CALLED"
    redirect_to Instagram.authorize_url(:redirect_uri => CALLBACK_URL)
  end

  def callback
    response = Instagram.get_access_token(params[:code], :redirect_uri => CALLBACK_URL)
    session[:access_token] = response.access_token
    redirect_to :controller => 'photos', :action => 'index'
  end
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, :notice => 'Tag was successfully created.' }
        format.json { render :json => @tag, :status => :created, :location => @tag }
      else
        format.html { render :action => "new" }
        format.json { render :json => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, :notice => 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Glamstagram</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/_form.html.haml
= form_for @photo do |f|
  -if @photo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:"
      %ul
        - @photo.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :source
    = f.text_field :source
  .actions
    = f.submit 'Save'

app/views/photos/edit.html.haml
%h1 Editing photo

= render 'form'

= link_to 'Show', @photo
\|
= link_to 'Back', photos_path

app/views/photos/index.html.haml
%h1= @user.username

= @recent_media_items.each do |media|
	%img{ :src => media.images.thumbnail.url }

app/views/photos/new.html.haml
%h1 New photo

= render 'form'

= link_to 'Back', photos_path

app/views/photos/show.html.haml
%p#notice= notice

%p
  %b Url:
  = @photo.url
%p
  %b User:
  = @photo.user_id
%p
  %b Source:
  = @photo.source

= link_to 'Edit', edit_photo_path(@photo)
\|
= link_to 'Back', photos_path

app/views/session/callback.html.haml
%h1 token
	= @token 

app/views/session/connect.html.haml
%h1 Sessions#connect
%p Find me in app/views/sessions/connect.html.erb

app/views/session/login.html.haml
%h1 login with instagram

.instagram_login
	= link_to image_tag('Instagram_Icon_Medium.png'), "/session/connect"

app/views/tags/_form.html.haml
= form_for @tag do |f|
  -if @tag.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tag.errors.count, "error")} prohibited this tag from being saved:"
      %ul
        - @tag.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/tags/edit.html.haml
%h1 Editing tag

= render 'form'

= link_to 'Show', @tag
\|
= link_to 'Back', tags_path

app/views/tags/index.html.haml
%h1 Listing tags

%table
  %tr
    %th
    %th
    %th

  - @tags.each do |tag|
    %tr
      %td= link_to 'Show', tag
      %td= link_to 'Edit', edit_tag_path(tag)
      %td= link_to 'Destroy', tag, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Tag', new_tag_path

app/views/tags/new.html.haml
%h1 New tag

= render 'form'

= link_to 'Back', tags_path

app/views/tags/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_tag_path(@tag)
\|
= link_to 'Back', tags_path

app/views/users/_form.html.haml
= form_for @user do |f|
  -if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.text_field :password
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Username
    %th Email
    %th Password
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.username
      %td= user.email
      %td= user.password
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Username:
  = @user.username
%p
  %b Email:
  = @user.email
%p
  %b Password:
  = @user.password

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path